import { useState } from "react";
import Head from "next/head";

export default function Home() {
  const [text, setText] = useState("");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          spellCheck={false}
          autoFocus
        />
        <pre aria-hidden>{text}</pre>
      </main>
    </div>
  );
}
